### PR TITLE
tic-tac-toe | week 1 hw

### PR DESCRIPTION
**Pull request by hlmbarnes**
Would love to know how to incorporate constructor for this project and if I can create a value for a background image change (vs using values of x and o).

### CODE REVIEW

**Comment by geluso** [comment]
Hey Hannah, I'm having trouble running your homework. At some point in your commit history you moved everything from style.css to css/main.css. This is fine, but you didn't update the link tag in index.html to point to the correct CSS file. When I load your page all I get is a blank white page.

When I fix the link to your CSS the page is still blank. Plus, now I get an error saying the page can't find "images/paper.jpg." This is probably due to you not adding your images directory and the image to your git repo. Remember to run these commands when making commits:

```
git status
git add -A
git commit -m "commit message"
```

`git status` should show all the files that are staged for commit. It will have two sections. One section says "changes not staged for commit" and another says "untracked files." When I create an images directory and add an image to it my git status looks like this:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   index.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    images/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by geluso** [comment]
Your script tag isn't formatted correctly. 

```
<script style.js></script>
```

remember to put the filename in the `src` attribute like this:

```
<script src="js/style.js"></script>
```

Also, it's strange to name your javascript something like "style." "tic-tac-toe.js" or "game.js" would be a more appropriate name. Style is usually a good name for CSS files.

**Comment by geluso** [comment]
After fixing the links to your CSS and JS I still don't see a board on the page. Did you ever get a board to appear on the page? You've got a lot of code written in your JavaScript and it looks like you have good ideas but I really can't get it to run. :/

Ok, let's check in together later.

**Comment by hlmbarnes** [comment]
so sorry Steve! My weird duplicate Sublime made two files and I didnt realize it. I committed many updates that I guess it didn't get and didn't push the correct files.

**Comment by geluso** [comment]
Ah, I've seen Sublime do that before. I'm not sure how it happens. That's annoying. Good luck figuring that out. I'm happy to take a look at it later.

**Pull request closed without merging**
