### PR TITLE
JS Tic-Tac-Toe HW

### PR DESCRIPTION
**Pull request by bengus101**
Pretty satisfied with my HTML & CSS. Still need to beef up my JS skills though.

### CODE REVIEW

**Comment by geluso** [comment]
Nice. I can tell you put some good work into this. Good HTML and CSS. I'm happy to see you got the boxes set up so that X's appear when you click on them. That's a necessary first step.

Your natural next step for this site is to ask yourself how to differentiate between who's turn it is and how to put either an X or an O in a square depending on who's turn it is.

You can keep track of turns a variety of ways. One good thing here turns out to be booleans. You can create one variable called something like `isTurnX = true` and use if statements to put in the Xs or Os accordingly.

```
if (isTurnX) {
  event.target.innerHTML = "X";
} else {
  event.target.innerHTML = "O";
}
isTurnX = !isTurnX;
```

The extra nice thing about using booleans to keep track of things that flip back and forth between each other is you can use the not operator `!` to flip the value back and forth.

I'd like to see you finish this assignment. You're well on your way. Everything you have up to here is totally solid.

**Comment by bengus101** [comment]
Hey Steve, I read your email about my tic-tac-toe. I pushed more changes to my repo just now. I was able to get the code to recognize different turns & throw up both X's & O's. It still needs a little more work-- namely coding up the winning combos & implementing the code to make the clear button work.
On a side note, I finished the temp converter assignment & would be keen to hear your thoughts on my solution. Respectfully,   
Ben Gustafson 

```
On Monday, March 28, 2016 9:02 PM, Steve Geluso <notifications@github.com> wrote:
```

 Nice. I can tell you put some good work into this. Good HTML and CSS. I'm happy to see you got the boxes set up so that X's appear when you click on them. That's a necessary first step.Your natural next step for this site is to ask yourself how to differentiate between who's turn it is and how to put either an X or an O in a square depending on who's turn it is.You can keep track of turns a variety of ways. One good thing here turns out to be booleans. You can create one variable called something like isTurnX = true and use if statements to put in the Xs or Os accordingly.if (isTurnX) {
  event.target.innerHTML = "X";
} else {
  event.target.innerHTML = "X";
}
isTurnX = !isTurnX;
The extra nice thing about using booleans to keep track of things that flip back and forth between each other is you can use the not operator ! to flip the value back and forth.I'd like to see you finish this assignment. You're well on your way. Everything you have up to here is totally solid. —

**Comment by geluso** [comment]
Sweet. I see your new changes to to tic tac toe and you're well on your way to completing the assignment. Your implementation of whosTurn and the changeTurn function is flawless.

You've written one piece of logic checking to see if someone won the top row. I'm sure you'd have no problem writing two more pieces of logic to check for the second and third rows. After that you can write three more pieces of logic to check for winning columns. Then two more to check either diagonal.

I encourage you to keep updating the page to get it to work completely.

You're at the point where you're writing high-quality code and you're ready to take a next step. Your next step is going to have yourself be able to identify redundancy in code and be able to reduce it. If we take some time to meet up I'll show you how you can write functions that generalize some of the code you're already writing.

Don't worry about redundancy right now. A great computer scientist (Donal Knuth) once famously said, "premature optimization is the root of all evil." It's better to write simple, functional code first and then take the time to reduce redundancy after it's written and patterns have presented themselves clearly.

**Comment by geluso** [comment]
Nice work. This is totally working. Have any specific questions?

Here's one thing I'd suggest: you can reduce the redundancy of writing click handlers for each individual cell if you store the values of each cell in an object. Instead of creating variables for each cell you can use strings like "Cell1", "Cell2" ... and so on to refer to the value of those cells in an object.

First create an object:

```
var cells = {
    'Cell1': undefined,
    'Cell2': undefined,
    'Cell3': undefined,
    'Cell4': undefined,
    'Cell5': undefined,
    'Cell6': undefined,
    'Cell7': undefined,
    'Cell8': undefined,
    'Cell9': undefined
};
```

Now, you can refer to the value of those cells using strings:

```
cells["Cell1"] = x;
```

And you can read their values when you check for wins like this:

```
if ((cells["Cell1"] == whosTurn && cells["Cell2"] == whosTurn && cells["Cell3"] == whosTurn) ||
    (cells["Cell4"] == whosTurn && cells["Cell5"] == whosTurn && cells["Cell6"] == whosTurn) ||
 ...
```

Notice that the strings in this object are the ids of each of the cells. You can take advantage of this and rewrite all your click handlers down to one function.

Here's your old code:

```
document.getElementById('Cell1').addEventListener('click', function(event){
    event.target.innerHTML = whosTurn;
    Cell1 = whosTurn;
    checkWinningCombos();
    changeTurn();
})
```

You can access the id of the element that's being clicked on with `event.target.id`. Here's what the new code would look like:

```
document.getElementById('Cell1').addEventListener('click', clickHandler);
document.getElementById('Cell2').addEventListener('click', clickHandler);
document.getElementById('Cell3').addEventListener('click', clickHandler);
...

function clickHandler(event){
    event.target.innerHTML = whosTurn;
    cells[event.target.id] = whosTurn;
    checkWinningCombos();
    changeTurn();
}
```

**Pull request closed without merging**
